import { PrismaClient } from '@prisma/client'
import { copyFileSync, existsSync } from 'fs'
import { resolve } from 'path'

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
}

// v1.8.3 — serverless schema bootstrap. On Vercel the SQLite database lives in
// ephemeral /tmp and starts EMPTY on every cold start; the build-time /tmp is a
// different machine, so `prisma db push` at build time cannot help. The bundle
// therefore ships a schema-only database (db/vercel-bootstrap.db, generated by
// scripts/vercel-build.sh from the current schema) and the first DB import of
// each cold instance copies it into place — only when the target is missing, so
// warm instances keep whatever data they accumulated.
const isVercel = process.env.VERCEL === '1'
const dbFile = process.env.DATABASE_URL?.replace(/^file:/, '') ?? ''
if (isVercel && dbFile.startsWith('/') && !existsSync(dbFile)) {
  const candidates = [
    resolve(process.cwd(), 'db/vercel-bootstrap.db'),
    resolve(process.cwd(), '../db/vercel-bootstrap.db'),
  ]
  const bootstrap = candidates.find((p) => existsSync(p))
  if (bootstrap) {
    try {
      copyFileSync(bootstrap, dbFile)
      console.log(`[zaimem:db] cold start — schema bootstrap copied into ${dbFile}`)
    } catch (e) {
      console.error('[zaimem:db] schema bootstrap copy failed:', e instanceof Error ? e.message : e)
    }
  } else {
    console.warn('[zaimem:db] schema bootstrap DB missing from bundle — first queries may hit missing tables (P2021)')
  }
}

export const db =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ['query'],
  })

// v1.8.2 — serverless guard: SQLite under file:/tmp is ephemeral per lambda
// instance. Warn loudly so no one mistakes a warm instance for persistence.
if (isVercel && dbFile && !dbFile.includes('/app/db/') && process.env.DATABASE_URL?.startsWith('file:')) {
  console.warn(
    '[zaimem:db] EPHEMERAL STORAGE: DATABASE_URL is a local SQLite file on Vercel — ' +
      'all data is lost on every cold start. Set DATABASE_URL to a managed Postgres ' +
      'connection string (schema.postgres.prisma is used automatically by the build).'
  )
}

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = db